export const items = [
  {
    id: 1,
    name: "Apple iPhone 13",
    price: 800,
    image: "./images/apple_iphone13.jpeg",
    quantity: 0,
  },
  {
    id: 2,
    name: "Nothing 3a",
    price: 459,
    image: "./images/nothing.jpeg",
    quantity: 0,
  },
  {
    id: 3,
    name: "Samsung S21",
    price: 1199,
    image: "./images/Samsung_S21.jpeg",
    quantity: 0,
  },
  {
    id: 4,
    name: "Redmi Note 10",
    price: 200,
    image: "./images/Redmi_Note10.jpeg",
    quantity: 0,
  },
  {
    id: 5,
    name: "OnePlus 9 Pro",
    price: 969,
    image: "./images/oneplusPro.jpeg",
    quantity: 0,
  },
  {
    id: 6,
    name: "Realme 15X",
    price: 226,
    image: "./images/realme15X.jpeg",
    quantity: 0,
  },
  {
    id: 7,
    name: "Samsung Galaxy",
    price: 1199,
    image: "./images/galaxy.jpg",
    quantity: 0,
  },
  {
    id: 8,
    name: "Xiaomi Mi 11",
    price: 220,
    image: "./images/XIOMI.png",
    quantity: 0,
  },
  {
    id: 9,
    name: "Motorola Razr",
    price: 1145,
    image: "./images/motorola.jpg",
    quantity: 0,
  },
  {
    id: 10,
    name: "HMD Crest Max",
    price: 999,
    image: "./images/hmd.webp",
    quantity: 0,
  },
  {
    id: 11,
    name: "Oppo Rene 13",
    price: 699,
    image: "./images/oppo.jpg",
    quantity: 0,
  },
  {
    id: 12,
    name: "iPhone 17 Pro",
    price: 1099,
    image: "./images/apple.jpeg",
    quantity: 0,
  },
];
